AiName: "落九千"
blivedm: #b站弹幕
  room_id: "1841952365" #b站直播间号
  sessdata: ""
  ACCESS_KEY_ID: "FGnIuK180gNOzpsxZlzuTpMx"
  ACCESS_KEY_SECRET: "SRIaxdh0vWtlBN1sHNdnQISO7TXShR"
  APP_ID: 1723755130622 # 在B站开放平台创建的项目ID
  ROOM_OWNER_AUTH_CODE: "DTZF5LI6KDMO6" # 在B站主播身份码
llm: #大模型聊天
  local_llm_type: 1
  qwen_url: "192.168.31.85:11434"
  split_flag: ",|，|。|!|！|?|？|\n" #流式回复的分割符
  split_limit: 4 #流式回复分割的最小字符数量
  public_sentiment_key: "(爱|喵|女仆|老婆|男朋友|比心|媳妇|喜欢|乖|不理你|美|老公)" #舆情关键字判断
nsfw: #鉴黄
  nsfw_server: "192.168.31.85:1801"
  filterEn: "huge breasts,open clothes,topless,voluptuous,breast,prostitution,erotic,armpit,milk,leaking,spraying,woman,cupless latex,latex,tits,boobs,lingerie,chest,seductive,poses,pose,leg,posture,alluring,milf,on bed,mature,slime,open leg,full body,bra,lace,bikini,full nude,nude,bare,one-piece,navel,cleavage,swimsuit,naked,adult,nudity,beautiful breasts,nipples,sex,Sexual,vaginal,penis,large penis,pantie,leotards,anal"
  filterCh: "奶子,乳房" #过滤弹幕
  progress_limit: 1 #绘图大于多少百分比进行鉴黄，这里设置了1%
  nsfw_limit: 0.2 #nsfw黄图值大于多少进行绘画屏蔽【值越大越是黄图，值范围0~1】
  nsfw_progress_limit: 0.2 #nsfw黄图-绘画进度鉴黄【值越大越是黄图，值范围0~1】